version: "3"
services:
  space-odometer:
    image: space_odometer_image
    container_name: odometer
    expose:
      - 55301
    labels:
      - traefik.enable=true
      - traefik.http.routers.space-odometer.rule=PathPrefix(`/space-odometer`)
      -
      - traefik.http.services.todo.loadbalancer.sticky=true
      - traefik.http.services.todo.loadbalancer.sticky.cookie.name=space-odometer-sticky-cookie
      - traefik.http.services.todo.loadbalancer.sticky.cookie.httpOnly=true
