version: "3"
services:
  space-odometer:
    image: space_odometer_image
    container_name: odometer
    expose:
      - 55301
    labels:
      - traefik.enable=true
      - traefik.http.routers.space-odometer.rule=PathPrefix(`/space-odometer`)
    networks:
      - revproxy


  traefik:
    image: traefik:2.6
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /traefik/traefik.yml:/traefik.yml:ro
      - /letsencrypt/acme.json:/acme.json

    labels:
      - traefik.enable=true
      - traefik.http.routers.dash.entrypoints=https
#      - traefik.http.routers.dash.rule=Host(`traefik.fragarie.dev`) || (Host(`fragarie.dev`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`)))
      - traefik.http.routers.dash.rule=Host(`traefik.fragarie.dev`)
      - traefik.http.routers.dash.service=api@internal
      - traefik.http.services.dash-traefik.loadbalancer.server.port=8089
      - traefik.http.middlewares.dash-auth.basicauth.users=admin:$$apr1$$3udne2qx$$yj78INxVzLPyo59jh86GY1
      - traefik.http.routers.dash.middlewares=dash-auth
    networks:
      - revproxy

networks:
  revproxy:
    external: true
